//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AGutierrezAeromexicoEntities : DbContext
    {
        public AGutierrezAeromexicoEntities()
            : base("name=AGutierrezAeromexicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pasajero> Pasajeroes { get; set; }
        public virtual DbSet<Reservacion> Reservacions { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vuelo> Vueloes { get; set; }
    
        public virtual int PasajeroAdd(string nombre, string apellidos)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PasajeroAdd", nombreParameter, apellidosParameter);
        }
    
        public virtual ObjectResult<UsuarioGetByUsername_Result> UsuarioGetByUsername(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioGetByUsername_Result>("UsuarioGetByUsername", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<VueloGetAll_Result> VueloGetAll(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VueloGetAll_Result>("VueloGetAll", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<PasajeroGetAll_Result> PasajeroGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PasajeroGetAll_Result>("PasajeroGetAll");
        }
    
        public virtual ObjectResult<VuelosGetAll_Result> VuelosGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VuelosGetAll_Result>("VuelosGetAll");
        }
    
        public virtual ObjectResult<VuelosPasajerosGetAll_Result> VuelosPasajerosGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VuelosPasajerosGetAll_Result>("VuelosPasajerosGetAll");
        }
    
        public virtual int ReservacionAdd(Nullable<int> idPasajero, Nullable<int> idVuelo)
        {
            var idPasajeroParameter = idPasajero.HasValue ?
                new ObjectParameter("IdPasajero", idPasajero) :
                new ObjectParameter("IdPasajero", typeof(int));
    
            var idVueloParameter = idVuelo.HasValue ?
                new ObjectParameter("IdVuelo", idVuelo) :
                new ObjectParameter("IdVuelo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReservacionAdd", idPasajeroParameter, idVueloParameter);
        }
    }
}
